Realised network implementation according to the sprint 6
DmitriiMM/MovieQuiz-ios pull request #4
Opened 2022-11-18 20:41 UTC by DmitriiMM

2022-11-19 10:04 UTC, mmbabaev requested changes

2022-11-19 10:04 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = true
при желании можно использовать `activityIndicator.hidesWhenStopped`
https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped

2022-11-19 10:04 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.questionFactory?.requestNextQuestion()
тут можно `self?`

2022-11-19 10:04 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +                let moviesList = try? JSONDecoder().decode(MostPopularMovies.self, from: data)
важно: 
нет обработки ошибки, если не прошел decode. Попробуйте в CodingKeys поменять название какого-то свойства (строку), скорее всего будет бесконечный индикатор

2022-11-19 10:15 UTC, DmitriiMM commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.questionFactory?.requestNextQuestion()
не понял, это вопрос? все работает значит можно self. На 110 строчке self необходим. в чем суть замечания?

2022-11-19 10:35 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.questionFactory?.requestNextQuestion()
строчки 
```
guard let self = self else { return }
self.questionFactory?.requestNextQuestion()
```
можно заменить на 
```
self?.questionFactory?.requestNextQuestion()
```
Это опциональное

2022-11-19 11:16 UTC, DmitriiMM commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = true
использовал это свойство во viewDidLoad

2022-11-19 11:17 UTC, DmitriiMM commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.questionFactory?.requestNextQuestion()
сделал так. меньше кода - лучше) спасибо

2022-11-19 11:18 UTC, DmitriiMM commented on MovieQuiz/Services/MoviesLoader.swift
> +                let moviesList = try? JSONDecoder().decode(MostPopularMovies.self, from: data)
дописал, отправил на проверку. вроде бы все работает

2022-11-19 13:35 UTC, DmitriiMM commented on MovieQuiz/Services/MoviesLoader.swift
> +                let moviesList = try? JSONDecoder().decode(MostPopularMovies.self, from: data)
в 7 спринте подглядел что в блок кэтч нужно передать handler(.failure(error)) вместо принта. в дальнейшем поправлю

2022-11-20 08:21 UTC, mmbabaev requested changes

2022-11-20 08:21 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +                    print("Failed to parse: \(error.localizedDescription)")
print - это не обработка ошибки. Попробуйте поменять CodingKeys в структуре (симулировать ошибку парсинга) и посмотреть что будет. 
Нужно вызвать `handler(.failure(error))`

2022-11-20 08:23 UTC, mmbabaev requested changes

2022-11-20 08:23 UTC, mmbabaev commented on MovieQuiz/Models/MostPopularMovies.swift
> +    init(from decoder: Decoder) throws {
это не критично, но для чего добавили?

2022-11-20 08:28 UTC, DmitriiMM commented on MovieQuiz/Models/MostPopularMovies.swift
> +    init(from decoder: Decoder) throws {
запутался в протоколах, что на что нужно подписать и пытался уйти от варнингов. В моменте все заработало и оставил так)

2022-11-20 12:17 UTC, mmbabaev approved these changes

2022-11-20 12:19 UTC, merged